# Generated by Django 5.1.7 on 2025-03-28 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_teste'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
